### ISSUE TITLE
Have to press back button if does not select any option in permission prompt

### ISSUE THREAD

**Issue by mkhizeryounas** [iam-mhaseeb/Photo-Editor-App#3]
Reinstall the app and try accessing gallery but do not select any option instead click away from the alert box and then try selecting any option (Camera or Gallery). You will need to click back button to remove a kind of overlay.

**Comment by iam-mhaseeb** [comment]
Can you share screenshot?

**Comment by iam-mhaseeb** [comment]
Kindly share a screenshot for better understanding of me.

**Comment by iam-mhaseeb** [comment]
I have fixed the issue, check the update now.
